spring.application.name=apiservice

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/apiservice}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.open-in-view=false

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100
